# Generated by Django 4.0.1 on 2022-03-15 01:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('restaurants', '0005_fooditem_alter_post_liked_by_restaurantimage_menu'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='liked_by',
            field=models.ManyToManyField(blank=True, related_name='likes_restaurants', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='restaurantimage',
            name='img',
            field=models.ImageField(upload_to='restaurant_pictures/'),
        ),
    ]
