# Generated by Django 4.0.1 on 2022-03-07 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_restaurant_followers_alter_restaurant_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='followers',
        ),
    ]
