# Generated by Django 3.2.12 on 2022-03-13 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0003_fooditem_menu'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='name',
            new_name='menu_name',
        ),
    ]
