# Generated by Django 3.2.12 on 2022-03-14 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0004_rename_name_menu_menu_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
