# Generated by Django 3.2.12 on 2022-03-14 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0004_alter_post_options_post_liked_by_alter_post_owner'),
        ('restaurants', '0005_alter_fooditem_name'),
    ]

    operations = [
    ]
